name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with pipenv
        run:|
          pip install pipenv
          pipenv install --deploy --dev
    - name: Run flake8 and mypy
        run:|
          pipenv run flake8
          pipenv run mypy
